In [2]:
import pandas as pd 
import numpy as np

In [3]:
A = pd.read_excel('./dados/mip/estimacao/MIP_2019_67_PCR.xlsx', sheet_name='An',skiprows=2,dtype={0:str})

In [4]:
#Concatenar os valores da primeira linha, a frente dos valotes da segunda linha, separando-os por '-'. 
A.loc[0,:] = A.loc[0,] + ' - ' + A.loc[1,]


In [5]:
#Remover a linha 1
A= A.drop(1).reset_index(drop=True)


In [6]:
A.loc[:,A.columns[0]] = A.loc[:,A.columns[0]] + ' - ' + A.loc[:,A.columns[1]]

In [7]:
A.head(2)

Código da Atividade Nível 67  \
0                                                NaN   
1  0191 - Agricultura, inclusive o apoio à agricu...   

                     Descrição da Atividade Nível 67  \
0                                                NaN   
1  Agricultura, inclusive o apoio à agricultura e...   

                                          Atividades  \
0  0191 - Agricultura, inclusive o apoio à agricu...   
1                                           0.021002   

                                      Unnamed: 3  \
0  0192 - Pecuária, inclusive o apoio à pecuária   
1                                       0.030474   

                                       Unnamed: 4  \
0  0280 - Produção florestal; pesca e aquicultura   
1                                         0.00442   

                                          Unnamed: 5  \
0  0580 - Extração de carvão mineral e de minerai...   
1                                           0.000093   

                                          Unnamed: 6  \
0  0680 - Extração de petróleo e gás, inclusive a...   
1                                           0.000038   

                                          Unnamed: 7  \
0  0791 - Extração de minério de ferro, inclusive...   
1                                           0.000087   

                                          Unnamed: 8  \
0  0792 - Extração de minerais metálicos não ferr...   
1                                           0.000094   

                                          Unnamed: 9  ...  \
0  1091 - Abate e produtos de carne, inclusive os...  ...   
1                                           0.024514  ...   

                                         Unnamed: 59  \
0  7880 - Outras atividades administrativas e ser...   
1                                           0.000667   

                                         Unnamed: 60  \
0  8000 - Atividades de vigilância, segurança e i...   
1                                           0.000005   

                                         Unnamed: 61              Unnamed: 62  \
0  8400 - Administração pública, defesa e segurid...  8591 - Educação pública   
1                                            0.00099                 0.001131   

               Unnamed: 63           Unnamed: 64           Unnamed: 65  \
0  8592 - Educação privada  8691 - Saúde pública  8692 - Saúde privada   
1                 0.000434              0.002269              0.000825   

                                         Unnamed: 66  \
0  9080 - Atividades artísticas, criativas e de e...   
1                                           0.000066   

                                         Unnamed: 67  \
0  9480 - Organizações associativas e outros serv...   
1                                           0.001716   

                 Atividades.7  
0  9700 - Serviços domésticos  
1                           0  

[2 rows x 69 columns]

In [8]:
A = A.drop(A.columns[1],axis=1)

In [9]:
idx = A.loc[1:,A.columns[0]]

In [10]:
A = A.loc[:,A.columns[1:]]

In [11]:
A.head(2)

Atividades  \
0  0191 - Agricultura, inclusive o apoio à agricu...   
1                                           0.021002   

                                      Unnamed: 3  \
0  0192 - Pecuária, inclusive o apoio à pecuária   
1                                       0.030474   

                                       Unnamed: 4  \
0  0280 - Produção florestal; pesca e aquicultura   
1                                         0.00442   

                                          Unnamed: 5  \
0  0580 - Extração de carvão mineral e de minerai...   
1                                           0.000093   

                                          Unnamed: 6  \
0  0680 - Extração de petróleo e gás, inclusive a...   
1                                           0.000038   

                                          Unnamed: 7  \
0  0791 - Extração de minério de ferro, inclusive...   
1                                           0.000087   

                                          Unnamed: 8  \
0  0792 - Extração de minerais metálicos não ferr...   
1                                           0.000094   

                                          Unnamed: 9  \
0  1091 - Abate e produtos de carne, inclusive os...   
1                                           0.024514   

                            Unnamed: 10                        Atividades.1  \
0  1092 - Fabricação e refino de açúcar  1093 - Outros produtos alimentares   
1                              0.547863                            0.222947   

   ...                                        Unnamed: 59  \
0  ...  7880 - Outras atividades administrativas e ser...   
1  ...                                           0.000667   

                                         Unnamed: 60  \
0  8000 - Atividades de vigilância, segurança e i...   
1                                           0.000005   

                                         Unnamed: 61              Unnamed: 62  \
0  8400 - Administração pública, defesa e segurid...  8591 - Educação pública   
1                                            0.00099                 0.001131   

               Unnamed: 63           Unnamed: 64           Unnamed: 65  \
0  8592 - Educação privada  8691 - Saúde pública  8692 - Saúde privada   
1                 0.000434              0.002269              0.000825   

                                         Unnamed: 66  \
0  9080 - Atividades artísticas, criativas e de e...   
1                                           0.000066   

                                         Unnamed: 67  \
0  9480 - Organizações associativas e outros serv...   
1                                           0.001716   

                 Atividades.7  
0  9700 - Serviços domésticos  
1                           0  

[2 rows x 67 columns]

In [12]:
A.loc[0,:]

Atividades      0191 - Agricultura, inclusive o apoio à agricu...
Unnamed: 3          0192 - Pecuária, inclusive o apoio à pecuária
Unnamed: 4         0280 - Produção florestal; pesca e aquicultura
Unnamed: 5      0580 - Extração de carvão mineral e de minerai...
Unnamed: 6      0680 - Extração de petróleo e gás, inclusive a...
                                      ...                        
Unnamed: 64                                  8691 - Saúde pública
Unnamed: 65                                  8692 - Saúde privada
Unnamed: 66     9080 - Atividades artísticas, criativas e de e...
Unnamed: 67     9480 - Organizações associativas e outros serv...
Atividades.7                           9700 - Serviços domésticos
Name: 0, Length: 67, dtype: object

In [13]:
A.columns = A.loc[0,:].values

In [14]:
A.loc[0,:]

0191 - Agricultura, inclusive o apoio à agricultura e a pós-colheita    0191 - Agricultura, inclusive o apoio à agricu...
0192 - Pecuária, inclusive o apoio à pecuária                               0192 - Pecuária, inclusive o apoio à pecuária
0280 - Produção florestal; pesca e aquicultura                             0280 - Produção florestal; pesca e aquicultura
0580 - Extração de carvão mineral e de minerais não metálicos           0580 - Extração de carvão mineral e de minerai...
0680 - Extração de petróleo e gás, inclusive as atividades de apoio     0680 - Extração de petróleo e gás, inclusive a...
                                                                                              ...                        
8691 - Saúde pública                                                                                 8691 - Saúde pública
8692 - Saúde privada                                                                                 8692 - Saúde privada
9080 - Atividades artíst

In [15]:
A = A.loc[1:,:]

In [16]:
A.set_index(idx,inplace=True)

In [17]:
#Achar a matriz inversa de Leontief 

I = np.eye(A.shape[0])
L = np.linalg.inv(I - A.astype(float))

In [ ]:
L.shape

(67, 67)

In [19]:
#Calcular o multiplicador de produção

multiplicador_producao = L.sum(axis=0)

In [20]:
multiplicador_producao

array([1.76076998, 1.87116443, 1.41138057, 1.89935165, 1.67881159,
       1.76928694, 1.8802768 , 2.57564418, 2.47674459, 2.37420239,
       2.30774523, 2.28124799, 2.02302138, 1.87938649, 2.01653526,
       2.00227036, 2.0858015 , 1.8218803 , 2.37981241, 2.33917418,
       1.98773497, 1.98266718, 2.132686  , 1.68216648, 2.03380282,
       2.14870885, 2.23407461, 2.13510503, 2.0267946 , 1.65617805,
       2.03842901, 1.88897226, 2.27793196, 2.05156181, 1.7170185 ,
       1.82193081, 1.70442506, 1.96355249, 1.55108011, 1.86247801,
       1.56797029, 2.02436096, 1.77533732, 1.8427104 , 1.576907  ,
       1.71720917, 1.87252457, 1.68490536, 1.85048103, 1.81316894,
       1.41260022, 1.44445913, 1.10515566, 1.40144171, 1.47456249,
       1.97057259, 1.480919  , 1.43721144, 1.24852401, 1.39124975,
       1.2296365 , 1.38620394, 1.50372377, 1.58168174, 1.58708887,
       1.64563588, 1.        ])

In [21]:
valor_adicionado = pd.read_excel('./dados/mip/estimacao/MIP_2019_67_PCR.xlsx', sheet_name='Usos',skiprows=140,dtype={0:str})

In [22]:
valor_adicionado = valor_adicionado[valor_adicionado.columns[0:69]]

In [24]:
valor_adicionado = valor_adicionado.drop('Unnamed: 1',axis=1)

In [26]:
valor_adicionado.rename(columns={'Unnamed: 0': 'Indice'}, inplace=True)

In [28]:
valor_adicionado = valor_adicionado.set_index('Indice')

In [78]:
valor_adicionado

Agricultura, inclusive o apoio à agricultura e a pós-colheita  \
Indice                                                                                                              
Valor adicionado bruto ( PIB )                                                                 206037               
Remunerações                                                                                    33120               
   Salários                                                                                     28069               
   Contribuições sociais efetivas                                                                5051               
      Previdência oficial /FGTS                                                                  5049               
      Previdência privada                                                                           2               
   Contribuições sociais imputadas                                                                  0               
Excedente operacional bruto e rendimento misto ...                                             178447               
   Rendimento misto bruto                                                                       97871               
   Excedente operacional bruto (EOB)                                                            80576               
Outros impostos sobre a produção                                                                 1990               
Outros subsídios à produção                                                                     -7520               
Valor da produção                                                                              415308               
Fator trabalho (ocupações)                                                                    6510033               

                                                    Pecuária, inclusive o apoio à pecuária  \
Indice                                                                                       
Valor adicionado bruto ( PIB )                                                       77092   
Remunerações                                                                         22497   
   Salários                                                                          19738   
   Contribuições sociais efetivas                                                     2759   
      Previdência oficial /FGTS                                                       2759   
      Previdência privada                                                                0   
   Contribuições sociais imputadas                                                       0   
Excedente operacional bruto e rendimento misto ...                                   53985   
   Rendimento misto bruto                                                            40745   
   Excedente operacional bruto (EOB)                                                 13240   
Outros impostos sobre a produção                                                       688   
Outros subsídios à produção                                                            -78   
Valor da produção                                                                   163008   
Fator trabalho (ocupações)                                                         5830589   

                                                    Produção florestal; pesca e aquicultura  \
Indice                                                                                        
Valor adicionado bruto ( PIB )                                                        27585   
Remunerações                                                                           2697   
   Salários                                                                            2357   
   Contribuições sociais efetivas                                                       340   
      Previdência oficial /FGTS                                                         338   
      Pre

In [75]:
valor_producao[0]

array([ 415308,  163008,   38200,   20360,  254621,  108090,   19375,
        322433,   52577,  331216,   90049,   16574,   56729,   69845,
         42405,   34007,  111870,   20083,  469698,   59796,  185375,
         97792,   52574,   78406,  125587,   88584,  144621,   78214,
        112667,  109228,   87853,  138666,  204019,  112190,   34106,
         82498,   81987,  345330,   88790,  572890, 1365064,  427944,
         24111,   48735,  148123,   31622,  300523,   18061,   44125,
        168740,  192225,  696739,  675910,  246830,   66918,  113009,
         53197,  282668,   45197,  897364,  380023,  149053,  217052,
        324104,   46576,  185099,   75158])

In [85]:
valor_producao = valor_adicionado.query(' index == "Valor da produção"').values[0]
ocupacoes = valor_adicionado.query(' index == "Fator trabalho (ocupações)"').values[0]
salarios = valor_adicionado.query(' index == "   Salários"').values[0]


In [86]:
participacao_ocupacao = ocupacoes / valor_producao
participacao_salarios = salarios / valor_producao

In [96]:
multiplicador_salario = participacao_salarios@ L
multiplicador_ocupacao = participacao_ocupacao@ L   

In [98]:
multiplicador_salario

array([0.15463597, 0.23073579, 0.11300397, 0.28458486, 0.15704336,
       0.14253006, 0.22893176, 0.29075544, 0.2587986 , 0.26829392,
       0.29408208, 0.2448277 , 0.3065162 , 0.36852972, 0.38859617,
       0.30790748, 0.26308469, 0.37699788, 0.12785316, 0.26501052,
       0.17512926, 0.21769549, 0.26053092, 0.26243311, 0.28361121,
       0.35279536, 0.23691782, 0.22575534, 0.30986222, 0.18579551,
       0.29033637, 0.31157812, 0.29167841, 0.32138623, 0.30586727,
       0.30293764, 0.25337493, 0.14894361, 0.27486093, 0.29473294,
       0.34058146, 0.30511725, 0.30222996, 0.25585421, 0.35052668,
       0.42203477, 0.29735169, 0.43349137, 0.41328978, 0.25610173,
       0.34572015, 0.29360527, 0.02964101, 0.30116113, 0.35931897,
       0.33452045, 0.27152036, 0.43837516, 0.60330397, 0.51124876,
       0.69823569, 0.58490396, 0.59170772, 0.373488  , 0.36562759,
       0.33113025, 0.97350914])

In [99]:
m_setor = np.zeros(multiplicador_producao.shape)

In [100]:
m_setor[0] = 415308

In [101]:
multiplicador_producao

array([1.76076998, 1.87116443, 1.41138057, 1.89935165, 1.67881159,
       1.76928694, 1.8802768 , 2.57564418, 2.47674459, 2.37420239,
       2.30774523, 2.28124799, 2.02302138, 1.87938649, 2.01653526,
       2.00227036, 2.0858015 , 1.8218803 , 2.37981241, 2.33917418,
       1.98773497, 1.98266718, 2.132686  , 1.68216648, 2.03380282,
       2.14870885, 2.23407461, 2.13510503, 2.0267946 , 1.65617805,
       2.03842901, 1.88897226, 2.27793196, 2.05156181, 1.7170185 ,
       1.82193081, 1.70442506, 1.96355249, 1.55108011, 1.86247801,
       1.56797029, 2.02436096, 1.77533732, 1.8427104 , 1.576907  ,
       1.71720917, 1.87252457, 1.68490536, 1.85048103, 1.81316894,
       1.41260022, 1.44445913, 1.10515566, 1.40144171, 1.47456249,
       1.97057259, 1.480919  , 1.43721144, 1.24852401, 1.39124975,
       1.2296365 , 1.38620394, 1.50372377, 1.58168174, 1.58708887,
       1.64563588, 1.        ])

In [102]:
multiplicador_ocupacao[0]*415308

np.float64(7963818.266433165)

In [93]:
np.dot(m_setor, multiplicador_ocupacao.T)

np.float64(7963818.266433165)

In [103]:
L.sum(axis=0)

array([1.76076998, 1.87116443, 1.41138057, 1.89935165, 1.67881159,
       1.76928694, 1.8802768 , 2.57564418, 2.47674459, 2.37420239,
       2.30774523, 2.28124799, 2.02302138, 1.87938649, 2.01653526,
       2.00227036, 2.0858015 , 1.8218803 , 2.37981241, 2.33917418,
       1.98773497, 1.98266718, 2.132686  , 1.68216648, 2.03380282,
       2.14870885, 2.23407461, 2.13510503, 2.0267946 , 1.65617805,
       2.03842901, 1.88897226, 2.27793196, 2.05156181, 1.7170185 ,
       1.82193081, 1.70442506, 1.96355249, 1.55108011, 1.86247801,
       1.56797029, 2.02436096, 1.77533732, 1.8427104 , 1.576907  ,
       1.71720917, 1.87252457, 1.68490536, 1.85048103, 1.81316894,
       1.41260022, 1.44445913, 1.10515566, 1.40144171, 1.47456249,
       1.97057259, 1.480919  , 1.43721144, 1.24852401, 1.39124975,
       1.2296365 , 1.38620394, 1.50372377, 1.58168174, 1.58708887,
       1.64563588, 1.        ])

In [104]:
#Criar um arquivo excel com 3 colunas, um multiplicador de producao, um de ocupacao e um de salário na mesma aba.

df_multiplicadores = pd.DataFrame({'multiplicador_producao': multiplicador_producao, 'multiplicador_ocupacao': multiplicador_ocupacao, 'multiplicador_salario': multiplicador_salario}, index=A.columns)

df_multiplicadores.to_excel('./dados/mip/estimacao/multiplicadores.xlsx', sheet_name='Multiplicadores')

In [109]:
valor_adicionado.index

Index(['Valor adicionado bruto ( PIB )', 'Remunerações', '   Salários',
       '   Contribuições sociais efetivas', '      Previdência oficial /FGTS',
       '      Previdência privada', '   Contribuições sociais imputadas',
       'Excedente operacional bruto e rendimento misto bruto',
       '   Rendimento misto bruto', '   Excedente operacional bruto (EOB)',
       'Outros impostos sobre a produção', 'Outros subsídios à produção',
       'Valor da produção', 'Fator trabalho (ocupações)'],
      dtype='object', name='Indice')

In [123]:
valor_producao

array([ 415308,  163008,   38200,   20360,  254621,  108090,   19375,
        322433,   52577,  331216,   90049,   16574,   56729,   69845,
         42405,   34007,  111870,   20083,  469698,   59796,  185375,
         97792,   52574,   78406,  125587,   88584,  144621,   78214,
        112667,  109228,   87853,  138666,  204019,  112190,   34106,
         82498,   81987,  345330,   88790,  572890, 1365064,  427944,
         24111,   48735,  148123,   31622,  300523,   18061,   44125,
        168740,  192225,  696739,  675910,  246830,   66918,  113009,
         53197,  282668,   45197,  897364,  380023,  149053,  217052,
        324104,   46576,  185099,   75158])

In [112]:
valor_pib = valor_adicionado.query(' index == "Valor adicionado bruto ( PIB )"').values[0]


In [124]:
df_producao = pd.DataFrame({'Valor de producao' : valor_producao})


In [125]:
df_producao.index = A.index

In [126]:
df_producao.to_excel('./dados/mip/estimacao/valor_producao.xlsx', sheet_name='Valor de Producao')